In [ ]:
#print hello world
print("Hello world")
print("Welcome to PDA")

Hello world
Welcome to PDA


In [ ]:
#indentation
print("I have no indentation")

I have no indentation


In [ ]:
#taking input()
name = input("Enter you name")
print("Hello",name,"Welcome!")

Enter you name niranjaNA


Hello niranjaNA Welcome!


In [ ]:
#printing output
s = "ABC"
age = 25
p = "India"
print(s,age,p)


ABC 25 India


In [ ]:
#taking multiple inputs
x,y,z=input("Enter three values:").split()
print("Total number of students:",x)
print("Total number of boys:",y)
print("Total number of girls:",z)

Enter three values: 44 22 33


Total number of students: 44
Total number of boys: 22
Total number of girls: 33


In [ ]:
#python varibales
x=55.7
s="Hello"
print(x)
print(s)


55.7
Hello


In [ ]:
#type casting a veraibles
i=int(x)
s1=str(x)
print(i)
print(s1)

55
55.7


In [ ]:
#getting typle of varible
n1=55
n2=55.6
n3="Hello"
n4=[1,2,3,4,5]
n5={"a":1,"b":2,"c":3}
n6=True
print(type(n1))
print(type(n2))
print(type(n3))
print(type(n4))
print(type(n5))
print(type(n6))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'dict'>
<class 'bool'>


In [ ]:
#python data types
#numeric data typess
a=5
print(type(a))
b=5.2
print(type(b))
c= 5 + 2j 
print(type(c))

<class 'int'>
<class 'float'>
<class 'complex'>


In [ ]:
#sequence data type
s="Welcome to PDA"
print(type(s))
print(s)
print(s[1])
print(s[-1])

<class 'str'>
Welcome to PDA
e
A


In [ ]:
#list
a=[]
print(type(a))
b=[1,2,3]
print(b)
c=[1,2.3,"A","Mango"]
print(c)
print(b[0])
print(b[1])
print(c[-1])
print(c[-2])

<class 'list'>
[1, 2, 3]
[1, 2.3, 'A', 'Mango']
1
2
Mango
A


In [ ]:
#tuples
t1=("Class","for","PDA")
t2=(1,2,3,4,5)
print(type(t1))
print(t2)
print(t1[-1])
print(t2[2])

<class 'tuple'>
(1, 2, 3, 4, 5)
PDA
3


In [ ]:
#boo;ean
print(type(False))
print(type(True))
if 1:
    print("1 is true")
else:
    print("0 is false")
    

<class 'bool'>
<class 'bool'>
1 is true


In [ ]:
#sets
s1=()
s2=("Beautiful day")
s3=set["A","B","C"]
print(type(s1))
print(s2)
for s in s3:
    print(s,end="")

<class 'tuple'>
Beautiful day
*set['A', 'B', 'C']

In [ ]:
#dictionary
d1={}
d2={"a":1,"b":2,"c":3}
d3={1:"a",2:"b",3:"c"}
print(d2)
print(d3[1])

{'a': 1, 'b': 2, 'c': 3}
a


In [ ]:
# type conversion
# implicit type conversion
x=10
y=10.8
z=x+y
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'float'>


In [ ]:
#explicit 
s="Hello World"
t=type(s)
u=list(s)
v=set(s)
print(type(s))
print(type(t))
print(type(u))
print(type(v))

<class 'str'>
<class 'type'>
<class 'list'>
<class 'set'>


In [ ]:
#operators
# arithmetic operators
a=17
b=5
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

22
12
85
3.4
3
2
1419857


In [ ]:
#comparison operators
a=7
b=5
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)
print(a!=b)
print(a==b)

True
False
True
False
True
False


In [ ]:
#logical operator
a=True
b=False
print(a and b)
print(a or b)
print(not b)


False
True
True


In [ ]:
#bitwise  operators
a=5
b=2
print(a&b)
print(a/b)
print(~a)
print(a^b)
print(a>>2)
print(a<<2)

0
2.5
-6
7
1
20


In [ ]:
##assignment operators
a=10
b=2
a+=b
print(a)
a-=b
print(a)
a>>=b
print(a)
a<<=b
print(a)

12
10
2
8


In [ ]:
# identify operators
a=10
b=5
c=a
print(c is a)
print(c is not b)

True
True


In [ ]:
#ternary operators
min=a if a<b else b
print(min)

5


In [ ]:
#membership operator
x=24
y=20
list1=[10,20,30,40]
if x not in list1:
    print("x not in list1")
if y in list1:
    print("y is in list1")

x not in list1
y is in list1


In [ ]:
# questions(find output)
print(100/10*10)
print(5-2+3)
print(5-(2+3))
print(2**3**2)

100.0
6
0
512


In [1]:
#if statement
a=3
if a>5:
    print("a is greater than 5")
else:
    print("a is not grater than 5")    

a is not grater than 5


In [4]:
#if elif statemnet
marks=85
if marks>=90:
    print("Grade A")
elif marks>=60:
    print("Grade B")
else:
    print("Negative number")

Grade B


In [5]:
#nested if else
num = 10
if num > 0:
    if num % 2 == 0:
        print("Positive Even number")
    else:
        print("postive odd number")
else:
    print("Negstivr number")

Positive Even number


In [6]:
#looping statemnt
#for loop
for i in range(1,6):
    print(i)



1
2
3
4
5


In [8]:
#while loop
i = 1
while i <= 5:
    print(i)
    i +=1

1
2
3
4
5


In [11]:
#break
for i in range(1,6):
    if i == 3:
        break
    print(i)

1
2


In [12]:
#continue statement
for i in range(1,6):
    if i == 3:
        continue
    print(i)

1
2
4
5


In [13]:
#pass statement
for i in range(5):
    if i == 3:
        pass
    print(i)

0
1
2
3
4


In [14]:
# match case
day = 2

match day:
    case 1:
        print("Monday")
    case 2:
        print("Tuesday")
    case 3:
        print("Wednesday")
    case _:
        print("Invalid day")

Tuesday


In [15]:
#ternary if else
n = 7
result = "Even" if n % 2 == 0 else "Odd"
print(result)

Odd


#Function

In [17]:
#function
def fun():
    print("Welcome")
fun()    

Welcome


In [18]:
#arugment passing:
def evenodd(x):
    if x%2==0:
        print("Even")
    else:
        print("Odd")
print(evenodd(15))
print(evenodd(16))
        

Odd
None
Even
None


In [19]:
#keyword argumnet
def student(fname , lname):
    print(fname , lname)
student(fname="practice",lname="Daily")
student(lname="Daily", fname="practice")

practice Daily
practice Daily


In [20]:
#default arguments
def myFun(x,y=20):
    print("x:",x)
    print("y:",y)
myFun(30)    

x: 30
y: 20


In [21]:
#positional arguments
def person(name,age):
    print("Hi Iam" ,name)
    print("Hi Iam",age)
print("case1")
person("Ram",25)
print("case2")
person(25,"Ram")

case1
Hi Iam Ram
Hi Iam 25
case2
Hi Iam 25
Hi Iam Ram


In [22]:
#function within function
def f1():
    s="I love you"
    def f2():
        print(s)
    f2()
f1()    

I love you


In [23]:
#pass by refernce
def myfun(x):
    x[0]=20
lst=[10,20,30,40,50]
print(lst)
myFun(lst)
print(lst)

[10, 20, 30, 40, 50]
x: [10, 20, 30, 40, 50]
y: 20
[10, 20, 30, 40, 50]


In [1]:
#pass by value
def myFun(x):
    x=20
a=20
print(a)
myFun(a)
print(a)
#a is not modified

20
20


In [2]:
#file handling
f = open("geek.txt","w")
f.write("File Handling Examples")
f.close()

In [3]:
#opening file
f=open("geek.txt", "r")
print(f)

<_io.TextIOWrapper name='geek.txt' mode='r' encoding='cp1252'>


In [4]:
## closing file
file=open("geek.txt","r")
#perform file opertions
file.close()

In [5]:
#checking file properties
f = open("geek.txt", "r")
print("Filename:", f.name)
print("Mode:", f.mode)
print("Is closed?:", f.closed)

Filename: geek.txt
Mode: r
Is closed?: False


In [6]:
#reading file
f = open("geek.txt", "r")
content= f.read()
print(content)
f.close()

File Handling Examples


In [7]:
#writing file
with open("geek.txt", "w") as file:
    file.write("Hello Python!\n")
    file.write("File Handling is easy with Pyrthon.")
print("File written successfully")

File written successfully


In [8]:
# using with statement
with open("geek.txt", "r") as file:
    content=file.read()
    print(content)

Hello Python!
File Handling is easy with Pyrthon.


In [9]:
# handling exceptions
try:
    file=open("geek.txt", "r")
    content = file.read()
    print(content)
finally:
    file.close()

Hello Python!
File Handling is easy with Pyrthon.


In [10]:
# Exception Handling
# basic example
n=10
try:
    res=n/0
except ZeroDivisionError:
    print("Can't be divided by Zero!")

Can't be divided by Zero!


In [11]:
try:
    n=0
    res=100/n

except ZeroDivisionError:
    print("You can't divided by Zero!") 

except ValueError:
    print("Enter a valid number!")

else:
    print("Result is", res)

finally:
    print("Execution complete.")
    

You can't divided by Zero!
Execution complete.


In [12]:
#catching specific exceptionas
try:
    x=int("str")
    inv=1/x

except ValueError:
    print("Not Valid!")

except ZeroDivisionError:
    print("Zero has no inverse!")

Not Valid!


In [13]:
# catching multiple exceptions
a=["10", "twenty", 30]

try:
    total=int(a[0]) + int(a[1])

except (ValueError, TypeError) as e:
    print("Error", e)

except IndexError:
    print("Index out of range")

Error invalid literal for int() with base 10: 'twenty'


In [14]:
# catching multiple exceptions
a=["10", "twenty", 30]

try:
    total=int(a[0]) + int(a[1])

except (ValueError, TypeError) as e:
    print("Error", e)

except IndexError:
    print("Index out of range")

Error invalid literal for int() with base 10: 'twenty'


In [15]:
# raise an exception
def set(age):
    if age<0:
        raise ValueError("Age cannot be negative")
    print(f"Age set to {age}")


In [16]:
#custom exceptions
class AgeError(Exception):
    pass

def set(age):
    if age<0:
        raise AgeError("Age cannot be negative.")
    print(f"Age set to {age}")
try:
    set(-5)
except AgeError as e:
    print(e)

Age cannot be negative.


#NUMPY

In [17]:
#CREATING NUMPY ARRAY
import numpy as np
#Crating a rank 1 Array
arr = np.array([1,2,3])
print(arr)
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
#ACCESSING ARRAY INDEX
import numpy as np
arr = np.array([[-1,2,0,4],
                [4,-0.5,6,0],
                [2.6,0,7,8],
                [3,-7,4,2.0]])
#Printing a range of Array
#with the use of slicing method
arr2 = arr[:2,::2]
print("first 2 rows and alternate columns(0and 2):/n",arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]
first 2 rows and alternate columns(0and 2):/n [[-1.  0.]
 [ 4.  6.]]


In [19]:
#priting element at
#specific Indices
arr3 = arr[[1,1,0,3],
    [3,2,1,0]]
print("/Element at indices(1,3),"
      "(1,2),(0,1),(3,0);/n",arr3)

/Element at indices(1,3),(1,2),(0,1),(3,0);/n [0. 6. 2. 3.]


In [18]:
#BASIC ARRAY OPERATIONS
import numpy as np
#Defining Array 1
a = np.array([[1,2],[3,4]])
#Defining Arrray 2
b =np.array([[4,3],[2,1]])
#Adding 1 to every element
print("Adding 1 to every elemnt:",a+1)
#Subtrating 2 from each element
print("/nSubtracting 2 from each elemnt:",b-2)
#sum of array elemnt
#Performing Binary operations
print("/nArray sum;/n",a+b)

Adding 1 to every elemnt: [[2 3]
 [4 5]]
/nSubtracting 2 from each elemnt: [[ 2  1]
 [ 0 -1]]
/nArray sum;/n [[5 5]
 [5 5]]


In [20]:
#MATHS OPERATIONS ON DATA TYPE ARRAY
import numpy as np

#First Array
arr1 = np.array([[4,7],[2,6]],
                dtype = np.float64)
#second Arraky
arr2 = np.array([[3,6],[2,8]],
                dtype = np.float64)
#Addition of two Array
sum=np.add(arr1,arr2)
print(sum)
#Squares root of Array
Sqrt = np.sqrt(arr1)
print(Sqrt)

#Transpose of Array
Trans_arr = arr1.T
print(Trans_arr)

[[ 7. 13.]
 [ 4. 14.]]
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


In [21]:
# BASIC SLICING AND INDEXING
import numpy as np  
a = np.arange(20)

print("a[15] =", a[15])
print("a[-8:17:1] =", a[-8:17:1])
print("a[10:] =", a[10:])

a[15] = 15
a[-8:17:1] = [12 13 14 15 16]
a[10:] = [10 11 12 13 14 15 16 17 18 19]


In [22]:
# ADVANCED INDEXING
import numpy as np
a = np.array( [[1, 2], [3, 4], [5, 6]] )
print( a[[0, 1, 2], [0, 0, 1]] )

[1 3 6]


In [23]:
# MATRIX OPERATIONS IN NUMPY
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Addition:\n", np.add(x, y))
print("Subtraction:\n", np.subtract(x, y))
print("Division:\n", np.divide(x, y))

Addition:
 [[ 8 10]
 [13 15]]
Subtraction:
 [[-6 -6]
 [-5 -5]]
Division:
 [[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [24]:
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Element-wise multiplication:\n", np.multiply(x, y))
print("Matrix multiplication:\n", np.dot(x, y))

Element-wise multiplication:
 [[ 7 16]
 [36 50]]
Matrix multiplication:
 [[25 28]
 [73 82]]


In [25]:
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Square root:\n", np.sqrt(x))
print("Sum of all elements:", np.sum(y))

print("Column-wise sum:", np.sum(y, axis=0))
print("Row-wise sum:", np.sum(y, axis=1))
print("Transpose:\n", x.T)

Square root:
 [[1.         1.41421356]
 [2.         2.23606798]]
Sum of all elements: 34
Column-wise sum: [16 18]
Row-wise sum: [15 19]
Transpose:
 [[1 4]
 [2 5]]


In [26]:
#Task : Print Checkboard pattern using numpy and  matrix concept
import numpy as np

n = 8  # size of checkerboard (8x8)

checkerboard = np.zeros((n, n), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
import numpy as np
# Creating NumPy arrays
# 1D array
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# 2D array
a2 = np.array([[1, 2],
               [3, 4],
               [5, 6],
               [7, 8]])

# 3D array
a3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

#pandas

In [30]:
import pandas as pd 
import numpy as np

s = pd.Series() 
print("Pandas Series: ", s) 
data = np.array(['g', 'e', 'e', 'k', 's']) 
  
s = pd.Series(data) 
print("Pandas Series:\n", s)

Pandas Series:  Series([], dtype: object)
Pandas Series:
 0    g
1    e
2    e
3    k
4    s
dtype: str


In [31]:
import pandas as pd 
   
df = pd.DataFrame() 
print(df)
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks'] 
  
df = pd.DataFrame(lst) 
print(df)

Empty DataFrame
Columns: []
Index: []
        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks


In [32]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
print(df.head())

   Unnamed: 0   name  age     city category  sales  a   b
0           0   John   25    Delhi        A    200  5  10
1           1   Riya   22   Mumbai        B    120  2   3
2           2   Aman   30     Pune        A    250  7   8
3           3   Neha   27  Kolkata        C    300  4   6
4           4  Arjun   35   Jaipur        B    200  1   9


In [33]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  13 non-null     int64
 1   name        10 non-null     str  
 2   age         13 non-null     int64
 3   city        10 non-null     str  
 4   category    10 non-null     str  
 5   sales       13 non-null     int64
 6   a           13 non-null     int64
 7   b           13 non-null     int64
dtypes: int64(5), str(3)
memory usage: 964.0 bytes
None


In [34]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
print(df.isnull().sum())
df = df.fillna(0)


Unnamed: 0    0
name          3
age           0
city          3
category      3
sales         0
a             0
b             0
dtype: int64


In [35]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
ages = df[df['age'] > 25]
print(ages)

    Unnamed: 0   name  age       city category  sales  a  b
2            2   Aman   30       Pune        A    250  7  8
3            3   Neha   27    Kolkata        C    300  4  6
4            4  Arjun   35     Jaipur        B    200  1  9
5            5    Jay   34  Bangalore        A    100  3  7
11          11  Arjun   35        NaN        B      0  1  9


In [36]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
df['total'] = df['a'] + df['b']
print(df.head())

   Unnamed: 0   name  age     city category  sales  a   b  total
0           0   John   25    Delhi        A    200  5  10     15
1           1   Riya   22   Mumbai        B    120  2   3      5
2           2   Aman   30     Pune        A    250  7   8     15
3           3   Neha   27  Kolkata        C    300  4   6     10
4           4  Arjun   35   Jaipur        B    200  1   9     10


In [37]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
print(df.info())


<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  13 non-null     int64
 1   name        10 non-null     str  
 2   age         13 non-null     int64
 3   city        10 non-null     str  
 4   category    10 non-null     str  
 5   sales       13 non-null     int64
 6   a           13 non-null     int64
 7   b           13 non-null     int64
dtypes: int64(5), str(3)
memory usage: 964.0 bytes
None


In [38]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
print(df.info())


<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  13 non-null     int64
 1   name        10 non-null     str  
 2   age         13 non-null     int64
 3   city        10 non-null     str  
 4   category    10 non-null     str  
 5   sales       13 non-null     int64
 6   a           13 non-null     int64
 7   b           13 non-null     int64
dtypes: int64(5), str(3)
memory usage: 964.0 bytes
None


In [39]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
ages = df[df['age'] > 25]
print(ages)


    Unnamed: 0   name  age       city category  sales  a  b
2            2   Aman   30       Pune        A    250  7  8
3            3   Neha   27    Kolkata        C    300  4  6
4            4  Arjun   35     Jaipur        B    200  1  9
5            5    Jay   34  Bangalore        A    100  3  7
11          11  Arjun   35        NaN        B      0  1  9


In [40]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
df['total'] = df['a'] + df['b']
print(df.head())


   Unnamed: 0   name  age     city category  sales  a   b  total
0           0   John   25    Delhi        A    200  5  10     15
1           1   Riya   22   Mumbai        B    120  2   3      5
2           2   Aman   30     Pune        A    250  7   8     15
3           3   Neha   27  Kolkata        C    300  4   6     10
4           4  Arjun   35   Jaipur        B    200  1   9     10


In [41]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
res = df.groupby('category')['sales'].sum()
print(res)


category
A    650
B    440
C    300
Name: sales, dtype: int64


In [42]:
import pandas as pd
df = pd.read_csv(r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
import pandas as pd 
s = pd.Series([10, 20, 30, 40])


In [43]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
s = pd.Series([85, 90, 78], index=["A", "B", "C"])
s["A"]


np.int64(85)

In [44]:
import pandas as pd
df = pd.read_csv(r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
s.iloc[0]        
# Access first element 
    # Access by label


np.int64(85)

In [45]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
s.mean(), s.max(), s.min()


(np.float64(84.33333333333333), np.int64(90), np.int64(78))

In [46]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
data = { 
"Name": ["Amit", "Riya", "Karan"], 
"Marks": [85, 90, 78] 
} 
df = pd.DataFrame(data)
df["Name"]


0     Amit
1     Riya
2    Karan
Name: Name, dtype: str

In [47]:
import pandas as pd
df = pd.read_csv (r"C:\Users\niranjana\OneDrive\Desktop\PDA\data.csv")
df.loc[0] 
df.iloc[1]


Unnamed: 0         1
name            Riya
age               22
city          Mumbai
category           B
sales            120
a                  2
b                  3
Name: 1, dtype: object